// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wrappers.proto

package com.hanwj.dubbo.type;

public interface DoubleValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hanwj.dubbo.type.DoubleValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The double value.
   * </pre>
   *
   * <code>double value = 1;</code>
   * @return The value.
   */
  double getValue();
}
