// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wrappers.proto

package com.hanwj.dubbo.type;

public interface FloatValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hanwj.dubbo.type.FloatValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The float value.
   * </pre>
   *
   * <code>float value = 1;</code>
   * @return The value.
   */
  float getValue();
}
