// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wrappers.proto

package com.hanwj.dubbo.type;

public interface Int32ValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hanwj.dubbo.type.Int32Value)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The int32 value.
   * </pre>
   *
   * <code>int32 value = 1;</code>
   * @return The value.
   */
  int getValue();
}
