// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wrappers.proto

package com.hanwj.dubbo.type;

public interface Int64ValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hanwj.dubbo.type.Int64Value)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The int64 value.
   * </pre>
   *
   * <code>int64 value = 1;</code>
   * @return The value.
   */
  long getValue();
}
