// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wrappers.proto

package com.hanwj.dubbo.type;

public interface BoolValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hanwj.dubbo.type.BoolValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The bool value.
   * </pre>
   *
   * <code>bool value = 1;</code>
   * @return The value.
   */
  boolean getValue();
}
