// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wrappers.proto

package com.hanwj.dubbo.type;

public interface BytesValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hanwj.dubbo.type.BytesValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The bytes value.
   * </pre>
   *
   * <code>bytes value = 1;</code>
   * @return The value.
   */
  com.google.protobuf.ByteString getValue();
}
