// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wrappers.proto

package com.hanwj.dubbo.type;

public interface StringValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hanwj.dubbo.type.StringValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The string value.
   * </pre>
   *
   * <code>string value = 1;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <pre>
   * The string value.
   * </pre>
   *
   * <code>string value = 1;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
