// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wrappers.proto

package com.hanwj.dubbo.type;

public interface UInt64ValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hanwj.dubbo.type.UInt64Value)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The uint64 value.
   * </pre>
   *
   * <code>uint64 value = 1;</code>
   * @return The value.
   */
  long getValue();
}
