// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DemoService.proto

package com.hanwj.dubbo.demo;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hanwj.dubbo.demo.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
