// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Persons.proto

package com.hanwj.dubbo.user;

public interface StaffOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hanwj.dubbo.user.Staff)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 3;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <pre>
   * list示例
   * </pre>
   *
   * <code>repeated .com.hanwj.dubbo.user.Staff.PhoneNumber phone = 4;</code>
   */
  java.util.List<com.hanwj.dubbo.user.Staff.PhoneNumber>
      getPhoneList();
  /**
   * <pre>
   * list示例
   * </pre>
   *
   * <code>repeated .com.hanwj.dubbo.user.Staff.PhoneNumber phone = 4;</code>
   */
  com.hanwj.dubbo.user.Staff.PhoneNumber getPhone(int index);
  /**
   * <pre>
   * list示例
   * </pre>
   *
   * <code>repeated .com.hanwj.dubbo.user.Staff.PhoneNumber phone = 4;</code>
   */
  int getPhoneCount();
  /**
   * <pre>
   * list示例
   * </pre>
   *
   * <code>repeated .com.hanwj.dubbo.user.Staff.PhoneNumber phone = 4;</code>
   */
  java.util.List<? extends com.hanwj.dubbo.user.Staff.PhoneNumberOrBuilder>
      getPhoneOrBuilderList();
  /**
   * <pre>
   * list示例
   * </pre>
   *
   * <code>repeated .com.hanwj.dubbo.user.Staff.PhoneNumber phone = 4;</code>
   */
  com.hanwj.dubbo.user.Staff.PhoneNumberOrBuilder getPhoneOrBuilder(
      int index);

  /**
   * <pre>
   * map示例
   * </pre>
   *
   * <code>.com.hanwj.dubbo.user.Staff.Map map = 5;</code>
   * @return Whether the map field is set.
   */
  boolean hasMap();
  /**
   * <pre>
   * map示例
   * </pre>
   *
   * <code>.com.hanwj.dubbo.user.Staff.Map map = 5;</code>
   * @return The map.
   */
  com.hanwj.dubbo.user.Staff.Map getMap();
  /**
   * <pre>
   * map示例
   * </pre>
   *
   * <code>.com.hanwj.dubbo.user.Staff.Map map = 5;</code>
   */
  com.hanwj.dubbo.user.Staff.MapOrBuilder getMapOrBuilder();
}
